import { ENEMY_SPRITES } from './spriteAssets.js';

export const ENEMY_DEFINITIONS = Object.freeze({
  normalBat: Object.freeze({
    id: 'normalBat',
    hp: 30,
    speed: 86,
    radius: 10,
    spriteUrl: ENEMY_SPRITES.bat,
    spriteSize: 20,
    contactDamage: 10,
    path: Object.freeze({
      amplitude: 58,
      frequency: 2.15,
      margin: 44,
    }),
  }),
  fastBat: Object.freeze({
    id: 'fastBat',
    hp: 18,
    speed: 126,
    radius: 8,
    spriteUrl: ENEMY_SPRITES.bat,
    spriteSize: 16,
    contactDamage: 8,
    defaultPathPatternId: 'straight',
    tags: Object.freeze(['fast', 'small']),
    path: Object.freeze({
      amplitude: 42,
      frequency: 2.4,
      margin: 44,
    }),
  }),
  heavyBat: Object.freeze({
    id: 'heavyBat',
    hp: 70,
    speed: 62,
    radius: 16,
    spriteUrl: ENEMY_SPRITES.bat,
    spriteSize: 32,
    contactDamage: 15,
    defaultPathPatternId: 'sCurve',
    tags: Object.freeze(['heavy']),
    path: Object.freeze({
      amplitude: 46,
      frequency: 1.65,
      margin: 48,
    }),
  }),
  eliteBat: Object.freeze({
    id: 'eliteBat',
    hp: 210,
    speed: 74,
    radius: 24,
    spriteUrl: ENEMY_SPRITES.bat,
    spriteSize: 48,
    contactDamage: 22,
    scoreValue: 6,
    defaultPathPatternId: 'sCurve',
    tags: Object.freeze(['elite']),
    path: Object.freeze({
      amplitude: 72,
      frequency: 1.85,
      margin: 56,
    }),
  }),
});
